### ISSUE TITLE
Handle corrupt images

### ISSUE THREAD

**Issue by bryan-lunt** [UIUC-CS547-2021sp-Group36/project#2]
```
Traceback (most recent call last):
  File "./src/Trainer.py", line 99, in <module>
    test_trainer.train(100)
  File "./src/Trainer.py", line 42, in train
    for batch_idx, ((Qs,Ps,Ns),l) in enumerate(self.dataloader):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.8/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
PIL.UnidentifiedImageError: Caught UnidentifiedImageError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/mnt/a/u/eot/bjlunt2/project/src/ImageLoader.py", line 133, in collate_fn
    positive_image_tensor = torch.stack([self.dataset[i][0] for i in positive_image_indices])
  File "/mnt/a/u/eot/bjlunt2/project/src/ImageLoader.py", line 133, in <listcomp>
    positive_image_tensor = torch.stack([self.dataset[i][0] for i in positive_image_indices])
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataset.py", line 257, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/opt/conda/lib/python3.8/site-packages/torchvision-0.6.0a0+b68adcf-py3.8-linux-x86_64.egg/torchvision/datasets/folder.py", line 135, in __getitem__
    sample = self.loader(path)
  File "/opt/conda/lib/python3.8/site-packages/torchvision-0.6.0a0+b68adcf-py3.8-linux-x86_64.egg/torchvision/datasets/folder.py", line 171, in default_loader
    return pil_loader(path)
  File "/opt/conda/lib/python3.8/site-packages/torchvision-0.6.0a0+b68adcf-py3.8-linux-x86_64.egg/torchvision/datasets/folder.py", line 153, in pil_loader
    img = Image.open(f)
  File "/opt/conda/lib/python3.8/site-packages/PIL/Image.py", line 2967, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BufferedReader name='/workspace/datasets/tiny-imagenet-200/train/n03980874/images/n03980874_480.JPEG'>
```

**Comment by bryan-lunt** [comment]
Delt with in some commit.
